### ISSUE TITLE
Enhacement: 2-finger scrolling

### ISSUE THREAD

**Issue by ejfox** [clwillingham/LEAP-OSXGestureController#4]
I'd love to be able to surf web pages by using two finger gestures. It fits particularly inline with my process for writing, where I have one space open will a full-screen text editor, and another screen with a web page open for reference. I'd love to be able to use the leap for everything but the writing.

Thanks so much for this!

Cheers!

**Comment by clwillingham** [comment]
thanks for the support, i really want to add this feature too, just trying to figure out how. i've just upgraded the project to 0.7.5 and new gesture support in the api adds some interesting possibilities. feel free to add any other gesture ideas you have to the issues list
